project:
  type: website

website:
  site-url: https://KAnetgeek.github.io/Website
  repo-url: https://github.com/KAnetgeek/Website
  title: "Kate Albrecht, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

